{% set name = "barrier3d" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UNC-CECL/Barrier3D/archive/v{{ version }}.tar.gz
  sha256: b3222029783150d7ebe26245d7ca72f16cff0029f760bf88bf1ffa7d097993fc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python
  entry_points:
    - b3d = barrier3d.cli:barrier3d


requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bmipy
    - click
    - distfit
    - matplotlib-base
    - numpy
    - pandas
    - pydantic
    - pyyaml

test:
  imports:
    - barrier3d
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/UNC-CECL/Barrier3D
  summary: "A spatially explicit exploratory model of barrier island evolution"
  description: |
    Barrier3D resolves cross-shore and alongshore topographic variations and
    simulates the morphological evolution of a barrier segment over time scales
    of years to centuries. The model explicitly yet efficiently simulates dune
    evolution, storm overwash, and a dynamically evolving shoreface in response
    to individual storm events and sea-level rise.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  doc_url: https://github.com/UNC-CECL/Barrier3D
  dev_url: https://github.com/UNC-CECL/Barrier3D

extra:
  recipe-maintainers:
    - mcflugen
